before:
  hooks:
    - go get github.com/eclipse/paho.mqtt.golang
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

nfpms:
  - id: foo
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    vendor: Herzmut Games Ltd.
    homepage: https://herzmut.games

    maintainer: Flipez <code@brauser.io>
    description: hkick-core
    formats:
      - deb
      - rpm
