builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goarch:
      - arm
    goarm:
      - 7

nfpms:
  - id: foo
    vendor: kickr
    homepage: https://kickr.me

    maintainer: Flipez <code@brauser.io>
    description: kickr-core
    formats:
      - deb

    files:
      "scripts/etc/systemd/system/kickr-core.service": "/etc/systemd/system/kickr-core.service"

    scripts:
      postinstall: "scripts/postinstall.sh"
      postremove: "scripts/postremove.sh"
