before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - arm
    goarm:
      - 7

nfpms:
  - id: foo
    vendor: Herzmut Games Ltd.
    homepage: https://herzmut.games

    maintainer: Flipez <code@brauser.io>
    description: hkick-core
    formats:
      - deb

    files:
      "scripts/etc/systemd/system/hkick-core.service": "/etc/systemd/system/hkick-core.service"

    scripts:
      postinstall: "scripts/postinstall.sh"
      postremove: "scripts/postremove.sh"
